# -*- coding: utf-8 -*-
import random

class Sex:

    """
    Calum Richard
    Davina Espinosa
    Khalid Xiong
    Amayah Grimes
    Harlan Briggs
    Alia Jenkins
    Declan Carrillo
    Kaylani Sullivan
    Evan Morris
    Genesis Buckley
    Aryan Bowen
    Dream Andrade
    Abdiel Horn
    Avah Patton
    Moises Huynh
    Oaklee Castillo
    Kai Morgan
    Delilah Moran
    Tate Hart
    Gemma Spears
    Ameer Pham
    Raelyn Morgan
    Hunter Rodgers
    Selah Orr
    Benicio Franklin
    Angela Foster
    Kayden Velazquez
    Jaliyah Chang
    Ari Cardenas
    Raven Costa
    Kenji Klein
    Elianna Faulkner
    Jabari Hunt
    Genevieve Glass
    Allan Jacobs
    Camilla McGee
    Conner Goodwin
    Shiloh Portillo
    Wallace Lowe
    Amari Hunt
    Jesus Lugo
    Kaylie Price
    Brooks Fox
    Juliette Cole
    Nathaniel Bowen
    Dream McIntyre
    Eliseo Herrera
    Ximena Delgado
    Colt Hurst
    Adalee Clark
    John McIntyre
    Rebekah Green
    Anthony McMahon
    Belen Powell
    Bennett Waters
    Bristol Bravo
    Genesis Osborne
    Shelby Huber
    Mac Levy
    Flora Doyle
    Kashton Gonzalez
    Abigail Navarro
    Reid Berry
    Annabelle Compton
    Abner Carr
    Rowan Cherry
    Rome Arias
    Aleah Brandt
    Damir Maldonado
    Elaina Chambers
    Orion O’Connor
    Charli Macdonald
    Hugh Callahan
    Kimber Arias
    Alec Sullivan
    Melanie Meyer
    Tristan Hester
    Zendaya Lopez
    Michael Hinton
    Jaelynn Blackburn
    Zahir Lawrence
    Lauren McDowell
    Lachlan Sharp
    Camryn Horton
    Garrett Blankenship
    Rosalee Holt
    Niko Burke
    Vera Schwartz
    Edwin Allison
    Chelsea Hubbard
    Forrest Parsons
    Maia Vega
    Aidan Kline
    Sevyn Shaw
    Elliot Murphy
    Bella Ellis
    Cole Keith
    Elyse Powell
    Bennett Hebert
    Kyleigh Robertson
    Emiliano Ho
    Calliope Owens
    Adriel Dougherty
    Alisson Erickson
    Johnny Spears
    Isabela Lopez
    Michael Sloan
    Selene Oliver
    Karson Shields
    Analia Kirk
    Alessandro Fox
    Juliette Potter
    Lucca Daugherty
    Magdalena Cannon
    Archie Sexton
    Ellen Caldwell
    Rylan Robles
    Felicity Thornton
    Malik Freeman
    Norah Chan
    Frank Strong
    Margo Portillo
    Wallace Waters
    Bristol Crosby
    Tristen Mathews
    Sloan Gray
    Nicholas Byrd
    Giselle Rogers
    Colton Landry
    Brynleigh Fernandez
    Bentley Davis
    Mia Wu
    Kyson Morrow
    Reyna Richardson
    Robert Cameron
    Julie Riley
    Amari Webster
    Kensley Bennett
    Leonardo Mendoza
    Cora Burton
    Zander Rowland
    Harleigh Cherry
    Rome Maynard
    Carolyn Camacho
    Tatum Xiong
    Amayah Cardenas
    Johnathan Avery
    Meghan Beasley
    Stanley Davila
    Rayne Pacheco
    Erik Bowman
    Fiona Barron
    Dustin Sweeney
    Yara Meyers
    Julien Harding
    Aniya Coleman
    Micah Santos
    Alana Delgado
    Colt Gardner
    Jordyn Hunt
    Jesus Moore
    Emily Bryan
    Jaxtyn Reilly
    Tori Humphrey
    Krew Stevens
    Katherine Stafford
    Alfredo Rosas
    Joelle Hardy
    Jayceon Evans
    Eliana Greene
    Griffin Stevens
    Katherine Goodman
    Philip Bradshaw
    Berkley Pollard
    Jad Flores
    Emilia Graham
    Giovanni Potter
    Rory Hull
    Salem Shaffer
    Alanna Hubbard
    Forrest Townsend
    Azalea Flynn
    Kannon Weaver
    Teagan Frost
    Dario Juarez
    Juliet Houston
    Sylas Garner
    Jacqueline Vasquez
    Rowan Hoover
    Virginia Hendrix
    Korbyn Bryant
    Parker Wang
    Cohen Gallagher
    Elliott Spears
    Ameer Sierra
    Marceline Flores
    Lincoln Lucero
    Ila Mejia
    Atticus Bell
    Melody West
    Diego Potter
    Rory Gordon
    Karter Gill
    Jordan Charles
    Conrad Corona
    Marianna Chan
    Frank Frederick
    Sariyah Booth
    Chaim Ortiz
    Anna Ayala
    Tanner Carroll
    Zara Sandoval
    Brantley Day
    Hayden Felix
    Rodney Moon
    Naya Craig
    Odin Aguilar
    Josie McMillan
    Rocky Bowers
    Elisa Wilcox
    Jerry Bryan
    Meredith Berger
    Byron Palacios
    Bria Sexton
    Mylo Little
    Harley Poole
    Quincy Chambers
    Makayla Maddox
    Lyric Fowler
    Lennon Palmer
    Theo Arellano
    Faye Dennis
    Emanuel Vo
    Artemis Roberts
    Josiah Lewis
    Ellie Carey
    Watson Carlson
    Kali Washington
    Juan Pineda
    Nola Johns
    Joziah Whitaker
    Ivanna Cruz
    Ryan Harmon
    Maren Reid
    Josue Munoz
    Kehlani Warren
    Abel Landry
    Brynleigh Bautista
    Raul Neal
    Talia Booker
    Dominik Dalton
    Lilian Page
    Pablo McDaniel
    Dahlia Sexton
    Mylo Yates
    Charley Bond
    Roger Norris
    Arielle Beil
    Ariel Zimmerman
    Ariyah Wilkins
    Yusuf Singleton
    Malaysia Spears
    Ameer House
    Sariah Stewart
    Nolan Riley
    Kayla Chung
    Ira Huerta
    Dulce Cordova
    Vicente Norman
    Malani Leon
    Marshall Black
    Molly Novak
    Bishop Calderon
    Serena Bond
    Roger York
    Milan Maddox
    Lyric Woodard
    Aubrie Holt
    Niko Potter
    Rory Rice
    Graham Mendez
    Londyn Garrett
    Kairo Sellers
    Mercy Schwartz
    Edwin Johns
    Giovanna Barry
    Emery Farley
    Wrenley Barrera
    Makai Lam
    Karina Walker
    Luke Garcia
    Amelia Cortes
    Banks Vincent
    Allyson Harrington
    Omari Warner
    Wynter Larsen
    Brycen Wood
    Natalia Montoya
    Ford Singh
    Vivienne Brandt
    Damir Mosley
    Zaniyah Murphy
    Cameron Lindsey
    Colette Garner
    Sage Dougherty
    Alisson Reynolds
    Vincent Lambert
    Nina Patton
    Moises Marsh
    Adelina McGee
    Conner Parker
    Aubrey Stanton
    Zyair Dyer
    Estrella Christian
    Ledger Owen
    Mikayla Maynard
    Landry Fox
    Juliette Zimmerman
    Sergio Fisher
    Arya Paul
    Noel Underwood
    Ensley Mann
    Nehemiah Mullen
    Shay Watson
    Greyson Lindsey
    Colette McFarland
    Dane Tate
    Skye Cline
    Cullen Holloway
    Mae Horton
    Garrett Austin
    Alivia Riley
    Amari Jimenez
    Adeline Rivera
    Charles Hampton
    Leona Barrera
    Makai Townsend
    Azalea Flores
    Lincoln Stark
    Kamilah Perez
    Owen Hobbs
    Lacey Bartlett
    Kace Glass
    Clare Valdez
    Kyler Barnes
    Liliana Knight
    Beckett Ray
    Ruth Sellers
    Madden Hood
    Briana Roy
    Marcelo Walters
    Samara Logan
    Rocco McCormick
    Macie Garcia
    James Parra
    Dalary Cobb
    Raphael Camacho
    Armani McIntyre
    Eliseo Hail
    Lainey Williamson
    Emerson Torres
    Violet Salinas
    Edgar Navarro
    Winter Compton
    Abner Carroll
    Zara Cano
    Terry Kaur
    Holland Alvarado
    Andres Blake
    Amanda Scott
    Leo Garrett
    Tessa Arias
    Alec Farrell
    Kassidy Stein
    Creed Owens
    Amaya Wilcox
    Jerry Bryant
    Parker Holmes
    King Calhoun
    Thalia Butler
    Ryder Reid
    Charlee Boyd
    Dean Campos
    Sutton Whitney
    Jeffery Rhodes
    Tatum Pollard
    Jad Beltran
    Kaydence Hammond
    Francis Peck
    Crystal Dean
    Ronan Pennington
    Yareli Ray
    Arlo Cervantes
    Aylin Reid
    Josue Fry
    Clarissa Reeves
    Clark Cervantes
    Aylin Martin
    Mateo Smith
    Olivia Griffith
    Franklin Nielsen
    Vienna Erickson
    Johnny Arellano
    Faye Rose
    Hayden Mathis
    Anne Castaneda
    Collin Kelley
    Rosalie Ball
    Shane Reyes
    Audrey Erickson
    Johnny Chambers
    Makayla Stanton
    Zyair Hardy
    Jessica House
    Yehuda Lambert
    Nina Gordon
    Karter Hart
    Gemma Wilcox
    Jerry Fitzgerald
    Marlee Shepherd
    Ronald Doyle
    Annalise Bender
    Zavier Campbell
    Addison Santiago
    Beckham Romero
    Eliza Allison
    Dennis Dougherty
    Alisson Salgado
    Trace Wade
    Evie Hardy
    Jayceon Wheeler
    Sydney Atkinson
    Duke Bernard
    Barbara Liu
    Pedro Huff
    Karsyn Jarvis
    Marlon Benitez
    Aliza McDowell
    Lachlan Rowe
    Matilda Garner
    Sage Pearson
    Kiara Fuentes
    Bowen Whitaker
    Ivanna Ramsey
    Luciano Wheeler
    Sydney Liu
    Pedro Robbins
    Stevie Bruce
    Uriah Hopkins
    Gabriela Mullen
    Shepard Cannon
    Noa Velasquez
    Sullivan Gentry
    Amelie Fischer
    Leonidas Glass
    Clare Hayes
    Legend Acosta
    Kaia Hickman
    Jakobe Webb
    Ariella Richards
    Holden Gallegos
    Ari Miranda
    Rory Kirk
    Ellis Strickland
    Keegan Cortes
    Lea Frye
    Franco Booth
    Zariyah Gaines
    Talon Wyatt
    Liberty Mora
    Arturo Cervantes
    Aylin Lu
    Duncan Harrell
    Kara Noble
    Idris Santiago
    Nyla Washington
    Juan Harrington
    Legacy Maxwell
    Eden Dixon
    Blakely Walsh
    Bodhi Villarreal
    Jazlyn Butler
    Ryder Vance
    Maxine Maxwell
    Eden McGuire
    April Murray
    Ashton Boyd
    Georgia McIntyre
    Eliseo Ellison
    Raina Blevins
    Avi Sullivan
    Melanie Enriquez
    Elisha Burgess
    Emory Rivers
    Bear Cochran
    Alma Donaldson
    Canaan Rice
    Ada Cohen
    Killian Molina
    Alexandria Barr
    Harley Holt
    Adelynn Collins
    Miles Escobar
    Erin Mosley
    Rayden Wilkins
    Amalia Trevino
    Jaime Parrish
    Tiana Ayala
    Tanner Peralta
    Malayah Riley
    Amari Massey
    Clementine Le
    Damien Lozano
    Cecelia Guerrero
    Bryce Williams
    Ava Lester
    Lee Trujillo
    Danielle Huber
    Mac Schmidt
    Kimberly Meadows
    Wayne Ward
    Ariana Ramos
    Angel Rogers
    Madelyn Booth
    Chaim Gross
    Angel Dougherty
    Brett Booker
    Nataly Flynn
    Kannon Watson
    Hailey Robles
    Otto Lowery
    Estelle Hickman
    Jakobe Odom
    Laylani Murillo
    Lance Weber
    Alayah Velazquez
    Drew Perry
    Clara Whitney
    Jeffery McLean
    Sky Cruz
    Ryan Lee
    Scarlett Weber
    Crew Fields
    Annie Wood
    Carson Hamilton
    Mackenzie Mason
    Brandon Carey
    Alora Jaramillo
    Riggs Espinoza
    Lucille English
    Junior Gross
    Angel Patterson
    Amir Russo
    Tinsley Mahoney
    Kamryn Lamb
    Amaia Carey
    Watson Cardenas
    Raven Moses
    Niklaus Glover
    Alessia Rosas
    Remi Gallagher
    Elliott Stevens
    Zachary Hickman
    Scarlette Riley
    Amari Arroyo
    Kyra Beck
    Eduardo Carpenter
    Lilly Avila
    Jaylen Sparks
    Aisha Walsh
    Bodhi Small
    Zaria Shaffer
    Dexter Jacobs
    Camilla Singh
    Louis Velasquez
    Esme Gentry
    Magnus Lozano
    Cecelia O’Connor
    Princeton Garrett
    Tessa Montgomery
    Maximiliano Delacruz
    Celine Gould
    Blaine Fuentes
    Madeleine Clarke
    Stetson Choi
    Karla Neal
    Kane Morris
    Genesis Wilson
    Daniel Vance
    Maxine West
    Diego Valenzuela
    Henley Shepard
    Damari Whitehead
    Sylvie Lynch
    Zane Casey
    Sylvia Berg
    Cayson Vaughn
    Reign Paul
    Noel Little
    Harley Griffith
    Franklin Ahmed
    Jolie Brandt
    Damir Soto
    Brynlee Hubbard
    Forrest Harrison
    Jasmine Bennett
    Leonardo Frost
    Paula Ware
    Tadeo Mercado
    Mckinley Swanson
    Hugo Nielsen
    Vienna Walker
    Luke Person
    Dylan Hall
    Thomas Arnold
    Finley McLaughlin
    Ibrahim Bernard
    Barbara Martinez
    Alexander McClure
    Estella Lopez
    Michael David
    Haylee Conway
    Orlando Fletcher
    Anaya Dillon
    Alvin Cantu
    Galilea Garza
    Judah Duffy
    Addisyn Howe
    Alaric Oliver
    Camille Reese
    Alijah Gibbs
    Carter Meza
    Lucian Truong
    Judith Griffith
    Franklin Rivers
    Kiana Willis
    Remington Boyle
    Aliya Walter
    Lochlan Norton
    Kylee Cuevas
    Brecken Benjamin
    Jianna Olsen
    Skyler Chandler
    Viviana Frank
    Braylen Maldonado
    Elaina Reese
    Alijah Rowland
    Harleigh Alvarez
    Xavier Martinez
    Harper Deleon
    Nasir Ellison
    Raina Chang
    Ari Novak
    Kaiya Price
    Brooks Lyons
    Kenzie Fleming
    Fernando Atkinson
    Jazmin Mendez
    Arthur Lloyd
    Emely Jarvis
    Marlon Gibbs
    Carter Jacobs
    Bryan Quintana
    Kenia Jenkins
    Declan Walters
    Samara Benitez
    Justice Weaver
    Teagan Duarte
    Abdullah Bernal
    Emmeline Shannon
    Eliel Waters
    Bristol Bowers
    Dorian Carroll
    Zara Bernal
    Eithan Odom
    Laylani O’Neal
    Eddie Dudley
    Hadleigh Barr
    Harley Atkinson
    Jazmin Collins
    Miles Taylor
    Sofia Underwood
    Reece Larson
    Alayna Barnett
    Stephen Esquivel
    Jaylee Harding
    Brodie Wiley
    Lauryn Lucero
    Felipe Dickerson
    Opal Cantu
    Anakin Palmer
    Juniper Bernal
    Eithan Roman
    Astrid Calhoun
    Gary Case
    Cleo Fowler
    Kameron Nash
    Novah Pham
    Russell Dawson
    Veronica Shields
    Devon Olson
    Isabel Martinez
    Alexander Ortega
    Lilah Wang
    Cohen Pineda
    Nola Kennedy
    Maxwell Schultz
    Briella Campos
    Gideon Buchanan
    Maryam Lara
    Caiden Stevenson
    Regina Shaffer
    Dexter Rush
    Maleah Mosley
    Rayden Wallace
    Arianna Sharp
    Royce Henson
    Kinslee Kim
    Roman Prince
    Greta Medrano
    Arian Christian
    Anahi Bates
    Ellis Vo
    Artemis Jimenez
    Silas Todd
    Zariah Robles
    Otto Mosley
    Zaniyah Bernal
    Eithan Munoz
    Kehlani Ingram
    Tripp Frederick
    Sariyah Reyes
    Eli Gross
    Angel Ramirez
    David Middleton
    Madalyn Landry
    Jaxx Cisneros
    Janelle Everett
    Camilo Bravo
    Amoura Powers
    Sean Small
    Zaria Villalobos
    Reuben Dillon
    Laurel Fry
    Jacoby Foster
    Brielle Decker
    Taylor Macias
    Adley Patton
    Moises Johnston
    Laila Hendrix
    Korbyn Fleming
    Fatima Patrick
    Derrick Martin
    Mila Craig
    Odin Ellison
    Raina Sanchez
    Joseph Underwood
    Ensley Rosas
    Remi McLean
    Sky Rogers
    Colton Rhodes
    Tatum Mathews
    Jamir Peralta
    Malayah Rivers
    Bear Archer
    Kadence Keith
    Jagger Vance
    Maxine Raymond
    Maurice Walter
    Penny Koch
    Salvador Russo
    Tinsley Nguyen
    Gabriel Quintana
    Kenia Mora
    Arturo Williams
    Ava Austin
    Omar Harding
    Aniya Craig
    Odin Michael
    Aubriella Donaldson
    Canaan Wallace
    Arianna Castro
    Jasper Short
    Cheyenne Avalos
    Coen Li
    Paige Waters
    Maximilian Cline
    Lina Gross
    Quinn Madden
    Violette Hodge
    Reign Sanford
    Emerald Jackson
    Sebastian Leblanc
    Novalee Mueller
    Albert Valencia
    Maddison Khan
    Kendrick Rush
    Maleah Le
    Damien Bates
    Madilyn Wolfe
    Donovan Petersen
    Fernanda Stevens
    Zachary Horne
    Marlowe Lopez
    Michael Pitts
    Nala Barnett
    Stephen Brock
    Jada Love
    Jeffrey Shaw
    Emersyn Glass
    Allan Wiley
    Lauryn Murray
    Ashton Humphrey
    Journi Miranda
    Rory O’Neill
    Kenna Bradshaw
    Emory Copeland
    Dayana Raymond
    Maurice Ali
    Zelda Proctor
    Vance Lindsey
    Colette McDaniel
    Major Salas
    Amber McCullough
    Briar Delarosa
    Iyla Kirby
    Tony Conner
    Alondra Woods
    Zion Rocha
    Emmie Huang
    Ayaan Tate
    Skye Robbins
    Finnegan Kane
    Ellianna Soto
    Barrett Monroe
    Carly Castaneda
    Collin Chang
    Ophelia Whitney
    Jeffery Harmon
    Maren Stein
    Creed Beck
    Gia Randall
    Trenton Nunez
    Mya Galvan
    Kingsley Ahmed
    Jolie Glover
    Mack Booker
    Nataly Calhoun
    Gary Ellis
    Ayla Jefferson
    Raylan Andersen
    Zoie Gardner
    Alan Webster
    Kensley Nash
    Chandler Howe
    Persephone Evans
    Elias Burke
    Vera Hogan
    Sonny Fitzpatrick
    Annabella Bowen
    Trevor McBride
    Kelsey Fowler
    Kameron Woodard
    Aubrie Jarvis
    Marlon Avalos
    Paloma Daugherty
    Turner Parker
    Aubrey Yoder
    Johan Chavez
    Nevaeh Hicks
    Maddox Hopkins
    Gabriela Simmons
    Harrison Shepard
    Noor Petersen
    Samson Romero
    Eliza McCarthy
    Devin Buchanan
    Maryam Anderson
    Jacob Armstrong
    Presley Le
    Damien Barber
    Cassidy Mayer
    Yahir Hebert
    Kyleigh Trevino
    Jaime Gilmore
    Chanel Vu
    Kamdyn Lozano
    Cecelia Soto
    Barrett Cline
    Lina Kline
    Ramon Gray
    Sarah Steele
    Elian Cameron
    Julie Harris
    Samuel Harmon
    Maren Vega
    Aidan Hinton
    Jaelynn Paul
    Noel Hunt
    Genevieve Adkins
    Kylo Townsend
    Azalea Sullivan
    Evan Frederick
    Sariyah Nava
    Stefan Gonzales
    Hadley Hood
    Brixton Sutton
    Izabella Garcia
    James Townsend
    Azalea Cortes
    Banks Morse
    Kairi Marsh
    Bo Heath
    Amani Branch
    Keenan Pitts
    Nala Blevins
    Avi Payne
    """ 

    first_name_female = [
        "Jadiel", "Leilany", "Keira", "Alexis", "Athena", "Savanna",
        "Mariah", "Juliette", "Eileen", "Esmeralda", "Harmony", "Milana",
        "Averie", "Karen", "Gabrielle", "Lilian", "Cameron", "Nova", "Valeria",
        "Samara", "Jaylah", "Rey", "Alexandra", "Malani", "Elisha", "Amalia",
        "Violeta", "Gracie", "Laylah", "Clementine", "Georgia", "Tinsley", 
        "Elaina", "Angela", "Claire", "Leia", "Carolyn", "Alijah", "Zoe"
        ]
    first_name_male = [
        "London", "Kai",
        "Mario", "Jimmy", "Bode", "Kamden", "Emiliano", "River", "Rodney", 
        "Alberto", "Saylor", "Kobe", "Riley", "Koa", "Keegan", "Caleb",
        "John", "Rowen", "Scott", "Lance", "Baker", "Remington", "Jaylee",
        "Emmalynn", "Talon", "Avery", "Elliot", "Axl", "Andres", "Christopher",
        "Duncan", "Damir", "Bentlee", "Jordan", "Ty", "Jamari", "Raegan", 
        "Rhys", "Frederick", "Madden", "Bishop", "Nicholas", "Seth", "Travis"
        ]
    last_name = [
        "Mays", "Stein", "Castillo", "Castaneda", "Townsend", "Butler",
        "Lambert", "Roy", "Vang", "Holland", "Morse", "Fox", "Rowe", "Ware", 
        "Robertson", "Garza", "Felix", "Baldwin", "Arroyo", "Mejia", "Ortega", 
        "Allen", "Weiss", "Robertson", "Strickland", "Koch", "Parker", "Rivas", 
        "Clark",  "Weeks", "Pratt", "Deleon", "McKenzie", "Dalton", "Murillo",
        "Esquivel", "Hartman", "Barker", "Murphy", "Dickson", "Moon", "Chen",
        "Campbell", "Ford", "Walters", "Shaw", "Beasley", "Magana", "Knight",
        "Strong", "Alvarado", "Gould", "Shields", "Enriquez", "Norman",
        "Berger", "Gaines", "Gregory", "Massey", "Boyd", "Manning", "Brandt", 
        "Gill", "Farrell", "Maldonado", "Valenzuela", "Dominguez", "Quinn", 
        "Franklin", "Wise", "Cruz", "Sellers", "Russo", "Novak", "Walsh", 
        "Case", "May", "Gray", "Finley", "Gillespie", "Reese", "Green",
        ]


    
    def __init__(self):
        self.first_name = ""
        self.surname = ""
        self.full_name = ""
        self.gender = ""


        self.setGender()
        self.setFullName()
    


    # ------------------------------------------------------------------
    # True if minion is female
    # ------------------------------------------------------------------
    def isFemale(self):
        i = False
        if self.getGender() == "female":
            i = True
        return i



    # ------------------------------------------------------------------
    # True if minion is male
    # ------------------------------------------------------------------
    def isMale(self):
        i = False
        if self.gender == "male":
            i = True
        return i

    
    # ------------------------------------------------------------------
    # Get minion's first name
    # ------------------------------------------------------------------
    def getFirstName(self):
        return self.first_name



    # ------------------------------------------------------------------
    # Get the full name
    # ------------------------------------------------------------------
    def getFullName(self):
        return self.full_name

    

    # ------------------------------------------------------------------
    # Get the male or female gender
    # ------------------------------------------------------------------
    def getGender(self):
        return self.gender
    
    

    # ------------------------------------------------------------------
    # Get minion's first name
    # ------------------------------------------------------------------
    def getSurname(self):
        return self.surname



    # ------------------------------------------------------------------
    # Set minion's full name
    # ------------------------------------------------------------------
    def setFullName(self):
        if self.isFemale():
            self.first_name = self.first_name_female[random.randint(0,len(self.first_name_female))-1]
            
        else:
            self.first_name = self.first_name_male[random.randint(0,len(self.first_name_male))-1]

        self.surname = self.last_name[random.randint(0,len(self.last_name))-1]
        
        self.full_name = self.first_name + " " + self.surname
        

    
    # ------------------------------------------------------------------
    # Set the gender male or female
    # ------------------------------------------------------------------
    def setGender(self):
        self.gender = "female"
        if random.randint(1,2) == 1:
            self.gender = "male"


